apiVersion: v1
kind: Secret
metadata:
  name: app-of-apps
  namespace: default
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  name: app-of-apps
  url: https://github.com/vagnerfls/App-Of-Apps.git