apiVersion: v1
kind: Secret
metadata:
  name: h-k
  namespace: argo-gaqs
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/vagnerfls/H-K.git